DROP TABLE IF EXISTS Book;

CREATE TABLE Book (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  Book_Name VARCHAR(250) NOT NULL,
  Author VARCHAR(250) NOT NULL,
  Available_Copies NUMERIC DEFAULT 0,
  Total_Copies NUMERIC DEFAULT 0
);